repos:
  - repo: 'https://github.com/psf/black'
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - '--line-length=120'
        files: src, tests
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - '--profile=black'
          - '--line-length=120'
        files: src, tests
  - repo: 'https://github.com/pycqa/flake8'
    rev: 4.0.1
    hooks:
      - id: flake8
        files: src, tests
        args:
          - '--max-line-length=120'
          - '--ignore=E203,W503,E501,W605'
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v0.942
    hooks:
      - id: mypy
        args:
          - '--install-types'
          - '--non-interactive'
          - '--ignore-missing-imports'
        files: src, tests